DROP_TABLES = """

DROP TABLE IF EXISTS public.LOCACAO;
DROP TABLE IF EXISTS public.ESTADO_VEICULO; 
DROP TABLE IF EXISTS public.RESERVA;
DROP TABLE IF EXISTS public.DISPONIBILIDADE; 

DROP TABLE IF EXISTS public.VAGAS;
DROP TABLE IF EXISTS public.VEICULO; 

DROP TABLE IF EXISTS public.PF;
DROP TABLE IF EXISTS public.PATIO;
DROP TABLE IF EXISTS public.SEGUROS;
DROP TABLE IF EXISTS public.PJ CASCADE;

"""
